/** Vendored dai DID-token verifier, checked against the shared fixture. */

import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { verifyDaiToken } from '../src/dai-token.ts'

interface Fixture {
  did: string
  aud: string
  now: number
  token: string
}

const fixture = JSON.parse(
  readFileSync(new URL('./fixtures/dai-token.json', import.meta.url), 'utf8'),
) as Fixture

describe('verifyDaiToken', () => {
  it('accepts the fixture generated by @aifeeds/did', () => {
    expect(verifyDaiToken(fixture.token, { aud: fixture.aud, now: fixture.now })).toEqual({ did: fixture.did })
  })

  it('refuses a different audience', () => {
    expect(verifyDaiToken(fixture.token, { aud: 'other', now: fixture.now })).toBeNull()
  })

  it('refuses an expired token', () => {
    expect(verifyDaiToken(fixture.token, { aud: fixture.aud, now: fixture.now + 10 * 60 * 1000 })).toBeNull()
  })

  it('refuses a token lifetime beyond the bound', () => {
    expect(verifyDaiToken(fixture.token, { aud: fixture.aud, now: fixture.now, maxTtlMs: 60_000 })).toBeNull()
  })

  it('refuses a tampered signature', () => {
    const [prefix, payload, signature] = fixture.token.split('.')
    if (signature === undefined) throw new Error('malformed fixture token')
    const flipped = signature.slice(0, -1) + (signature.endsWith('0') ? '1' : '0')
    expect(verifyDaiToken(`${prefix}.${payload}.${flipped}`, { aud: fixture.aud, now: fixture.now })).toBeNull()
  })

  it('refuses a tampered payload', () => {
    const [prefix, , signature] = fixture.token.split('.')
    const forged = Buffer.from(JSON.stringify({
      v: 1,
      did: fixture.did,
      aud: 'other',
      iat: fixture.now,
      exp: fixture.now + 300_000,
      nonce: 'forged',
    })).toString('base64url')
    expect(verifyDaiToken(`${prefix}.${forged}.${signature}`, { aud: fixture.aud, now: fixture.now })).toBeNull()
  })

  it('rejects a replayed nonce', () => {
    const seenNonces = new Set<string>()
    expect(verifyDaiToken(fixture.token, { aud: fixture.aud, now: fixture.now, seenNonces })).not.toBeNull()
    expect(verifyDaiToken(fixture.token, { aud: fixture.aud, now: fixture.now, seenNonces })).toBeNull()
  })
})

import { DidTokenAuthenticator } from '../src/dai-token.ts'
import type { ConnectionIndexRequest, ConnectionIndexResponse, ConnectionTrustRequest } from '../src/rpc.ts'

function trust(authorization?: string): ConnectionTrustRequest {
  const headers: Record<string, string> = { host: 'dsh.example' }
  if (authorization !== undefined) headers.authorization = authorization
  return { headers } as unknown as ConnectionTrustRequest
}

describe('DidTokenAuthenticator', () => {
  it('accepts the fixture DID token and refuses a foreign owner', () => {
    const auth = new DidTokenAuthenticator({ audience: fixture.aud, now: () => fixture.now })
    expect(auth.isAuthenticated(trust(`DSH ${fixture.token}`))).toBe(true)
    expect(auth.isAuthenticated(trust())).toBe(false)
    const pinned = new DidTokenAuthenticator({ audience: fixture.aud, ownerDid: 'did:key:zOther', now: () => fixture.now })
    expect(pinned.isAuthenticated(trust(`DSH ${fixture.token}`))).toBe(false)
  })

  it('serves the index only with a valid dsh_token query', () => {
    const auth = new DidTokenAuthenticator({ audience: fixture.aud, now: () => fixture.now })
    const response = { writeHead: () => undefined, end: () => undefined } as unknown as ConnectionIndexResponse
    const request = (url: string): ConnectionIndexRequest =>
      ({ url, method: 'GET', headers: {} }) as unknown as ConnectionIndexRequest
    expect(auth.authorizeIndex(request(`/?dsh_token=${encodeURIComponent(fixture.token)}`), response)).toBe(true)
    expect(auth.authorizeIndex(request('/'), response)).toBe(false)
  })
})
