/**
 * Vendored verifier for dai's DID-signed dsh token (`@aifeeds/did/dshauth`).
 *
 * Format: `dsha1.<base64url payload>.<signature hex>`, signature over
 * `sha256(payloadB64)` under the holder's `did:key`. ML-DSA (bigtangle-ts
 * `SignatureBundle`) and Ed25519 are verified; the audience, time window, and an
 * optional replay nonce set are enforced. A fixture generated by `@aifeeds/did`
 * (tests/fixtures/dai-token.json) guards this copy against drift.
 */

import { createHash, createPublicKey, verify as cryptoVerify } from 'node:crypto'
import { Sha256Hash } from 'bigtangle-ts/dist/net/bigtangle/core/Sha256Hash.js'
import { PQKey } from 'bigtangle-ts/dist/net/bigtangle/crypto/pq/PQKey.js'
import { SignatureBundle } from 'bigtangle-ts/dist/net/bigtangle/crypto/pq/SignatureBundle.js'
import type { ConnectionAuthenticator } from './browser-auth.ts'
import type {
  ConnectionIndexRequest,
  ConnectionIndexResponse,
  ConnectionTrustRequest,
} from './rpc.ts'

const TOKEN_PREFIX = 'dsha1'
const DEFAULT_TTL_MS = 5 * 60 * 1000
const MLDSA_PREFIXED_CODEC = 0x300001
const ED25519_CODEC = 0xed01
const BASE58_ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'
// SPKI DER prefix for an Ed25519 raw public key.
const ED25519_SPKI_PREFIX = Buffer.from('302a300506032b6570032100', 'hex')

/** The signed statement carried by a dsh token. */
export interface DaiTokenPayload {
  v: 1
  did: string
  aud: string
  iat: number
  exp: number
  nonce: string
}

/** Verification policy: expected audience, clock, and optional replay set. */
export interface DaiVerifyOptions {
  aud: string
  now?: number
  maxTtlMs?: number
  clockSkewMs?: number
  seenNonces?: Set<string>
}

function hexToBytes(value: string): Buffer | undefined {
  if (!/^[0-9a-fA-F]*$/.test(value) || value.length % 2 !== 0) return undefined
  return Buffer.from(value, 'hex')
}

function decodeBase58(value: string): Buffer | undefined {
  let zeros = 0
  while (zeros < value.length && value[zeros] === '1') zeros++
  const bytes: number[] = []
  for (const character of value.slice(zeros)) {
    let carry = BASE58_ALPHABET.indexOf(character)
    if (carry < 0) return undefined
    for (let i = 0; i < bytes.length; i++) {
      carry += (bytes[i] ?? 0) * 58
      bytes[i] = carry & 0xff
      carry >>= 8
    }
    while (carry > 0) {
      bytes.push(carry & 0xff)
      carry >>= 8
    }
  }
  return Buffer.concat([Buffer.alloc(zeros), Buffer.from(bytes.reverse())])
}

function decodeUvarint(bytes: Buffer, offset: number): { value: number; length: number } | undefined {
  let value = 0
  let shift = 0
  for (let i = offset; i < bytes.length; i++) {
    const byte = bytes[i]
    if (byte === undefined) return undefined
    value |= (byte & 0x7f) << shift
    if ((byte & 0x80) === 0) return { value, length: i - offset + 1 }
    shift += 7
    if (shift > 28) return undefined
  }
  return undefined
}

/** Extract the multicodec and raw public key from a `did:key:z…` identifier. */
function didPubkey(did: string): { codec: number; pub: Buffer } | undefined {
  if (!did.startsWith('did:key:z')) return undefined
  const decoded = decodeBase58(did.slice('did:key:z'.length))
  if (decoded === undefined) return undefined
  const prefix = decodeUvarint(decoded, 0)
  if (prefix === undefined) return undefined
  return { codec: prefix.value, pub: decoded.subarray(prefix.length) }
}

function verifySignature(did: string, digest: Buffer, signatureHex: string): boolean {
  const key = didPubkey(did)
  const signature = hexToBytes(signatureHex)
  if (key === undefined || signature === undefined) return false
  if (key.codec === MLDSA_PREFIXED_CODEC) {
    try {
      const bundle = SignatureBundle.deserialize(signature)
      return PQKey.verify(Sha256Hash.wrap(digest), bundle, key.pub)
    } catch {
      return false
    }
  }
  if (key.codec === ED25519_CODEC && key.pub.length === 32) {
    try {
      const publicKey = createPublicKey({
        key: Buffer.concat([ED25519_SPKI_PREFIX, key.pub]),
        format: 'der',
        type: 'spki',
      })
      return cryptoVerify(null, digest, publicKey, signature)
    } catch {
      return false
    }
  }
  return false
}

/**
 * Verify a dsh DID token: signature, audience, time window, and optional replay.
 * @returns the bound principal, or null when the token is not valid.
 */
export function verifyDaiToken(token: string, options: DaiVerifyOptions): { did: string } | null {
  const parts = token.split('.')
  if (parts.length !== 3) return null
  const [prefix, payloadB64, signature] = parts
  if (prefix !== TOKEN_PREFIX || !payloadB64 || !signature) return null
  let payload: DaiTokenPayload
  try {
    payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf8')) as DaiTokenPayload
  } catch {
    return null
  }
  if (payload.v !== 1
    || typeof payload.did !== 'string'
    || typeof payload.aud !== 'string'
    || typeof payload.iat !== 'number'
    || typeof payload.exp !== 'number'
    || typeof payload.nonce !== 'string') {
    return null
  }
  const now = options.now ?? Date.now()
  const skew = options.clockSkewMs ?? 30_000
  const maxTtl = options.maxTtlMs ?? DEFAULT_TTL_MS
  if (payload.aud !== options.aud) return null
  if (payload.exp <= now) return null
  if (payload.iat > now + skew) return null
  if (payload.exp - payload.iat > maxTtl) return null
  const digest = createHash('sha256').update(payloadB64).digest()
  if (!verifySignature(payload.did, digest, signature)) return null
  if (options.seenNonces !== undefined) {
    if (options.seenNonces.has(payload.nonce)) return null
    options.seenNonces.add(payload.nonce)
  }
  return { did: payload.did }
}

function headerValue(headers: ConnectionTrustRequest['headers'], name: string): string | undefined {
  if (headers instanceof Headers) return headers.get(name) ?? undefined
  const value = headers[name]
  return typeof value === 'string' ? value : undefined
}

/**
 * {@link ConnectionAuthenticator} for a DID-signed token instead of the
 * process launch token. The bearer arrives as `Authorization: DSH <token>` (or
 * a `dsh_token` query parameter on the index); an optional owner DID pins the
 * runtime to one principal.
 */
export class DidTokenAuthenticator implements ConnectionAuthenticator {
  private readonly audience: string
  private readonly ownerDid?: string
  private readonly now?: () => number
  private readonly seenNonces = new Set<string>()

  constructor(options: { audience: string; ownerDid?: string; now?: () => number }) {
    this.audience = options.audience
    if (options.ownerDid !== undefined) this.ownerDid = options.ownerDid
    if (options.now !== undefined) this.now = options.now
  }

  /** The verified principal for a request, or undefined when it is not valid. */
  private principal(request: ConnectionTrustRequest, token?: string | null): string | undefined {
    const header = headerValue(request.headers, 'authorization')
    const raw = header?.startsWith('DSH ') ? header.slice(4).trim() : token ?? undefined
    if (!raw) return undefined
    const verified = verifyDaiToken(raw, {
      aud: this.audience,
      seenNonces: this.seenNonces,
      ...(this.now !== undefined ? { now: this.now() } : {}),
    })
    if (verified === null) return undefined
    if (this.ownerDid !== undefined && verified.did !== this.ownerDid) return undefined
    return verified.did
  }

  isAuthenticated(request: ConnectionTrustRequest): boolean {
    return this.principal(request) !== undefined
  }

  authorizeIndex(request: ConnectionIndexRequest, response: ConnectionIndexResponse): boolean {
    const fromQuery = new URL(request.url ?? '/', 'http://dsh.invalid').searchParams.get('dsh_token')
    if (this.principal(request, fromQuery) !== undefined) return true
    response.writeHead(401, {
      'cache-control': 'no-store',
      'content-type': 'text/plain; charset=utf-8',
    })
    response.end(request.method === 'HEAD' ? undefined : 'dai DID authentication required\n')
    return false
  }

  authenticatedUrl(baseUrl: string): string {
    return baseUrl
  }
}
